#!/bin/bash
cmdpath=$(readlink $0 -f || echo $0)
cd $(dirname $cmdpath)

first=$1
second=$2

if [ -z "$first" ] && [ -z "$second" ]; then
  node index.js
elif [ $first == "list" ]; then
  node index.js list
elif [ $first == "nm" ] && [ $second ]; then
  node index.js nm $second
elif [ $first == "nm" ] && [ -z "$second" ]; then
  node index.js nm
else
  node index.js $first $second
fi
